<?
$bgcol='#FFFFFF';
$alltb_bgc='#FFFFFF';
$alltb_borc='#E8E8E8';
$comm_adborder='#eaeaea';
$comm_adbgcol='#FFFFFF';
$comm_cuborder='#eaeaea';
$comm_cuscol='#FFFFFF';
$repl_border='#eaeaea';
$repl_bgcol='#FFFFFF';
$co_w_namebox='#252525';
$co_w_namefcol='#FFFFFF';
$co_w_textbox='#FFFFFF';
$co_w_textborder='#eaeaea';
$co_m_textbox='#FFFFFF';
$co_m_textborder='#eaeaea';
$co_w_submit='#FFFFFF';
$co_w_submit_fontcol='#252525';
$co_w_submit_border='#eaeaea';
$beu_te_bgcol='#FFFFFF';
$beu_te_bordercol='#eaeaea';
$beu_bt_fontcolor='#252525';
$beu_bt_col='#FFFFFF';
$beu_bt_bodercol='#eaeaea';
$comm_morecol='#FFFFFF';
$comm_morebgcol='#252525';
$comm_moreborder='#252525';
?>
