<?
$option_ip='off';
$pagebar_type='on';
$link_http='on';
$en_num='off';
$restrict_del='on';
$reple_mode='off';
$kdreply_mode='on';
$img_mode='off';
$mem_login='off';
$reply_close='off';
?>
